/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AttendanceDAO;
import dao.SchoolClassDAO;
import dao.SubjectDAO;
import dao.TeachingAssignmentDAO;
import model.SchoolClass;
import model.Subject;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import model.TeachingAssignment;

/**
 *
 * @author Lenovo
 */
public class AttendanceFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AttendanceFrm.class.getName());
    private DefaultTableModel tableModel;

    private final SchoolClassDAO classDAO = new SchoolClassDAO();
    private final SubjectDAO subjectDAO = new SubjectDAO();
    private final AttendanceDAO attendanceDAO = new AttendanceDAO();
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    private final Map<Integer, Integer> rowToStudentId = new HashMap<>();
    private static final String[] STATUS_OPTIONS = {"Present", "Absent", "Late", "ExcusedAbsence"};

    private final model.User currentUser;
    private final TeachingAssignmentDAO teachingAssignmentDAO = new TeachingAssignmentDAO();
    private List<TeachingAssignment> teacherAssignments;

    /**
     * Creates new form AttendanceFrm
     */
    public AttendanceFrm(model.User currentUser) {
        this.currentUser = currentUser;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        customizeUI();
        loadCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        cboClass = new javax.swing.JComboBox<>();
        lblSubject = new javax.swing.JLabel();
        cboSubject = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnLoad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("ĐIỂM DANH");

        lblClass.setText("Lớp:");

        lblSubject.setText("Môn học:");

        lblDate.setText("Ngày (dd/MM/yyyy):");

        btnLoad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLoad.setText("Tải danh sách");
        btnLoad.addActionListener(this::btnLoadActionPerformed);

        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HS", "Họ tên", "Trạng thái", "Ghi chú"
            }
        ));
        jScrollPane1.setViewportView(tblAttendance);

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Lưu điểm danh");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(253, 253, 253)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBack)
                                .addGap(1, 1, 1)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClass)
                    .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubject)
                    .addComponent(cboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        SchoolClass selectedClass = (SchoolClass) cboClass.getSelectedItem();
        Subject selectedSubject = (Subject) cboSubject.getSelectedItem();
        Date date = parseDate(txtDate.getText().trim());
        if (selectedClass == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp!");
            return;
        }
        if (selectedSubject == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn môn học!");
            return;
        }
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Ngày không đúng định dạng dd/MM/yyyy!");
            return;
        }
        // KIỂM TRA PHÂN CÔNG GIÁO VIÊN
        if (currentUser.getRoleId() == 2) {
            boolean allowed = false;
            int classId = selectedClass.getId();
            int subjectId = selectedSubject.getId();
            for (TeachingAssignment ta : teacherAssignments) {
                int assignmentClassId = ta.getSchoolClassId();
                int assignmentSubjectId = ta.getSubjectId();
                if (assignmentClassId == classId&& assignmentSubjectId == subjectId) {
                    allowed = true;
                    break;
                }
            }
            if (!allowed) {
                JOptionPane.showMessageDialog(this,"Bạn không được phân công dạy môn này ở lớp này!");
                return;
            }
        }
        tableModel.setRowCount(0);
        rowToStudentId.clear();
        List<Object[]> rows = attendanceDAO.getAttendanceByClassDate(selectedClass.getId(), selectedSubject.getId(), date);
        int row = 0;
        for (Object[] r : rows) {
            tableModel.addRow(new Object[]{r[1], r[2], r[3], r[4] == null ? "" : r[4]});
            rowToStudentId.put(row, (Integer) r[0]);
            row++;
        }
        if (rows.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có học sinh trong lớp này!");
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Subject selectedSubject = (Subject) cboSubject.getSelectedItem();
        Date date = parseDate(txtDate.getText().trim());

        if (selectedSubject == null || date == null || tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng tải danh sách trước khi lưu!");
            return;
        }

        int successCount = 0;
        for (int row = 0; row < tableModel.getRowCount(); row++) {
            Integer studentId = rowToStudentId.get(row);
            if (studentId == null) {
                continue;
            }
            String status = (String) tableModel.getValueAt(row, 2);
            String note = (String) tableModel.getValueAt(row, 3);

            boolean ok = attendanceDAO.saveAttendance(studentId, selectedSubject.getId(), date, status, note, null);
            if (ok) {
                successCount++;
            }
        }
        JOptionPane.showMessageDialog(this, "Đã lưu điểm danh cho " + successCount + " học sinh!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainMenuFrm(currentUser).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    private void customizeUI() {
        tableModel = new DefaultTableModel(new Object[]{"Mã HS", "Họ tên", "Trạng thái", "Ghi chú"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2 || column == 3; // chỉ Trạng thái và Ghi chú cho sửa
            }
        };
        tblAttendance.setModel(tableModel);

        // Cột "Trạng thái" (index 2) hiển thị ComboBox ngay trong ô khi double-click
        JComboBox<String> statusCombo = new JComboBox<>(STATUS_OPTIONS);
        tblAttendance.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(statusCombo));

        txtDate.setText(sdf.format(new java.util.Date())); // mặc định ngày hôm nay
    }

    private void loadCombos() {
        cboClass.removeAllItems();
        cboSubject.removeAllItems();
        // ADMIN
        if (currentUser.getRoleId() == 1) {
            for (SchoolClass c : classDAO.getAll()) {
                cboClass.addItem(c);
            }
            for (Subject s : subjectDAO.getAll()) {
                cboSubject.addItem(s);
            }
            return;
        }

        // GIÁO VIÊN
        if (currentUser.getRoleId() == 2) {
            teacherAssignments = teachingAssignmentDAO.getByTeacherUserId(currentUser.getId());
            // Chỉ load các lớp giáo viên được phân công
            for (TeachingAssignment ta : teacherAssignments) {
                if (!containsClass(ta.getSchoolClassId())) {
                    SchoolClass schoolClass = new SchoolClass();
                    schoolClass.setId(ta.getSchoolClassId());
                    schoolClass.setClassName(ta.getClassName());
                    cboClass.addItem(schoolClass);
                }
            }
            // Khi chọn lớp thì lọc môn
            cboClass.addActionListener(e -> loadSubjectsBySelectedClass());
            // Load môn của lớp đầu tiên
            if (cboClass.getItemCount() > 0) {
                cboClass.setSelectedIndex(0);
                loadSubjectsBySelectedClass();
            }
        }
    }

    private void loadSubjectsBySelectedClass() {
        cboSubject.removeAllItems();
        SchoolClass selectedClass = (SchoolClass) cboClass.getSelectedItem();
        if (selectedClass == null || teacherAssignments == null) {
            return;
        }
        for (TeachingAssignment ta : teacherAssignments) {
            if (ta.getSchoolClassId() == selectedClass.getId()) {
                Subject subject = new Subject();
                subject.setId(ta.getSubjectId());
                subject.setSubjectName(ta.getSubjectName());
                subject.setSubjectCode(ta.getSubjectCode());
                cboSubject.addItem(subject);
            }
        }
    }

    private boolean containsClass(int classId) {
        for (int i = 0; i < cboClass.getItemCount(); i++) {
            SchoolClass c = cboClass.getItemAt(i);
            if (c.getId() == classId) {
                return true;
            }
        }
        return false;
    }

    private boolean containsSubject(int subjectId) {
        for (int i = 0; i < cboSubject.getItemCount(); i++) {
            Subject s = cboSubject.getItemAt(i);
            if (s.getId() == subjectId) {
                return true;
            }
        }
        return false;
    }

    private Date parseDate(String text) {
        try {
            return new Date(sdf.parse(text).getTime());
        } catch (ParseException e) {
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<SchoolClass> cboClass;
    private javax.swing.JComboBox<Subject> cboSubject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblAttendance;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
