/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.SchoolClassDAO;
import dao.TeacherDAO;
import model.SchoolClass;
import model.TeacherProfile;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import model.User;

/**
 *
 * @author Lenovo
 */
public class ClassManagementFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClassManagementFrm.class.getName());
    private final User currentUser;
    private final SchoolClassDAO classDAO = new SchoolClassDAO();
    private final TeacherDAO teacherDAO = new TeacherDAO();
    private DefaultTableModel tableModel;
    private int selectedId = -1;

    /**
     * Creates new form ClassManagementFrm
     */
    public ClassManagementFrm(User currentUser) {
        this.currentUser = currentUser;

        initComponents();

        setLocationRelativeTo(null);

        customizeUI();
        loadTeacherCombo();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClasses = new javax.swing.JTable();
        lblClassName = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        lblGrade = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();
        lblSchoolYear = new javax.swing.JLabel();
        txtSchoolYear = new javax.swing.JTextField();
        lblTeacher = new javax.swing.JLabel();
        cboTeacher = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("QUẢN LÝ LỚP HỌC");

        tblClasses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên lớp", "Khối", "Năm học", "GVCN "
            }
        ));
        jScrollPane1.setViewportView(tblClasses);

        lblClassName.setText("Tên lớp:");

        lblGrade.setText("Khối:");

        lblSchoolYear.setText("Năm học:");

        lblTeacher.setText("GVCN:");

        cboTeacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdate)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDelete)
                                        .addGap(51, 51, 51)
                                        .addComponent(btnClear))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGrade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtGrade)
                                            .addComponent(cboTeacher, 0, 165, Short.MAX_VALUE))))))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassName)
                    .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrade)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSchoolYear)
                    .addComponent(txtSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeacher)
                    .addComponent(cboTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customizeUI() {
        tableModel = new DefaultTableModel(new Object[]{"ID", "Tên lớp", "Khối", "Năm học", "GVCN"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblClasses.setModel(tableModel);
        tblClasses.getSelectionModel().addListSelectionListener(e -> onRowSelected());
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            SchoolClass c = new SchoolClass();
            c.setClassName(txtClassName.getText().trim());
            c.setGradeLevel(Integer.parseInt(txtGrade.getText().trim()));
            c.setSchoolYear(txtSchoolYear.getText().trim());
            TeacherProfile t = (TeacherProfile) cboTeacher.getSelectedItem();
            c.setHomeroomTeacherId(t != null ? t.getId() : null);
            if (classDAO.insert(c)) {
                JOptionPane.showMessageDialog(this, "Thêm lớp thành công!");
                loadTable();
                btnClearActionPerformed(null);
            } else {
                JOptionPane.showMessageDialog(this, "Thêm lớp thất bại!");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Khối phải là số nguyên!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (selectedId < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 lớp trong bảng!");
            return;
        }
        try {
            SchoolClass c = new SchoolClass();
            c.setId(selectedId);
            c.setClassName(txtClassName.getText().trim());
            c.setGradeLevel(Integer.parseInt(txtGrade.getText().trim()));
            c.setSchoolYear(txtSchoolYear.getText().trim());
            TeacherProfile t = (TeacherProfile) cboTeacher.getSelectedItem();
            c.setHomeroomTeacherId(t != null ? t.getId() : null);
            if (classDAO.update(c)) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                loadTable();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Khối phải là số nguyên!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedId < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 lớp trong bảng!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Xóa lớp này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            classDAO.delete(selectedId);
            loadTable();
            btnClearActionPerformed(null);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        selectedId = -1;
        txtClassName.setText("");
        txtGrade.setText("");
        txtSchoolYear.setText("");
        tblClasses.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainMenuFrm(currentUser).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    private void loadTeacherCombo() {
        cboTeacher.removeAllItems();
        for (TeacherProfile t : teacherDAO.getAll()) {
            ((JComboBox) cboTeacher).addItem(t);
        }
    }

    private void loadTable() {
        tableModel.setRowCount(0);
        for (SchoolClass c : classDAO.getAll()) {
            tableModel.addRow(new Object[]{c.getId(), c.getClassName(), c.getGradeLevel(), c.getSchoolYear(), c.getHomeroomTeacherName()});
        }
    }

    private void onRowSelected() {
        int row = tblClasses.getSelectedRow();
        if (row < 0) {
            return;
        }
        selectedId = (int) tableModel.getValueAt(row, 0);
        txtClassName.setText((String) tableModel.getValueAt(row, 1));
        txtGrade.setText(String.valueOf(tableModel.getValueAt(row, 2)));
        txtSchoolYear.setText((String) tableModel.getValueAt(row, 3));
        String teacherName = (String) tableModel.getValueAt(row, 4);
        for (int i = 0; i < cboTeacher.getItemCount(); i++) {
            TeacherProfile item = (TeacherProfile) ((JComboBox) cboTeacher).getItemAt(i); // ép raw type rồi cast
            if (item.getFullName() != null && item.getFullName().equals(teacherName)) {
                cboTeacher.setSelectedIndex(i);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboTeacher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClassName;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblSchoolYear;
    private javax.swing.JLabel lblTeacher;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblClasses;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtSchoolYear;
    // End of variables declaration//GEN-END:variables
}
