/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.GradeDAO;
import dao.SchoolClassDAO;
import dao.StudentDAO;
import dao.SubjectDAO;
import model.Grade;
import model.SchoolClass;
import model.StudentProfile;
import model.Subject;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import dao.TeachingAssignmentDAO;
import model.TeachingAssignment;

/**
 *
 * @author Lenovo
 */
public class GradeEntryFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GradeEntryFrm.class.getName());
    private final SchoolClassDAO classDAO = new SchoolClassDAO();
    private final SubjectDAO subjectDAO = new SubjectDAO();
    private final StudentDAO studentDAO = new StudentDAO();
    private final GradeDAO gradeDAO = new GradeDAO();
    private final TeachingAssignmentDAO teachingAssignmentDAO = new TeachingAssignmentDAO();
    private List<TeachingAssignment> teacherAssignments;
    private DefaultTableModel tableModel;

    // Map dòng bảng -> StudentProfileId để lưu điểm đúng học sinh
    private final Map<Integer, Integer> rowToStudentId = new HashMap<>();
    private final model.User currentUser;

    /**
     * Creates new form GradeEntryFrm
     */
    public GradeEntryFrm(model.User currentUser) {
        this.currentUser = currentUser;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        customizeUI();
        loadCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        cboClass = new javax.swing.JComboBox<>();
        lblSubject = new javax.swing.JLabel();
        cboSubject = new javax.swing.JComboBox<>();
        lblExamType = new javax.swing.JLabel();
        cboExamType = new javax.swing.JComboBox<>();
        lblSemester = new javax.swing.JLabel();
        txtSemester = new javax.swing.JTextField();
        btnLoad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrades = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("NHẬP ĐIỂM");

        lblClass.setText("Lớp:");

        lblSubject.setText("Môn học:");

        lblExamType.setText("Loại điểm:");

        lblSemester.setText("Học kỳ:");

        btnLoad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLoad.setText("Tải danh sách");
        btnLoad.addActionListener(this::btnLoadActionPerformed);

        tblGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HS", "Họ tên", "Điểm"
            }
        ));
        jScrollPane1.setViewportView(tblGrades);

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Lưu điểm");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(228, 228, 228)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblExamType)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cboExamType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(lblSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboSubject, 0, 165, Short.MAX_VALUE)
                                .addComponent(txtSemester))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(23, 23, 23)
                                .addComponent(btnBack)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClass)
                    .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubject)
                    .addComponent(cboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExamType)
                    .addComponent(cboExamType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemester)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        SchoolClass selectedClass= (SchoolClass) cboClass.getSelectedItem();
        Subject selectedSubject= (Subject) cboSubject.getSelectedItem();
        String examType= (String) cboExamType.getSelectedItem();
        String semester= txtSemester.getText().trim();

        // KIỂM TRA
        if (selectedClass == null) {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn lớp!");
            return;
        }
        if (selectedSubject == null) {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn môn học!");
            return;
        }
        if (examType == null) {
            JOptionPane.showMessageDialog(this,"Vui lòng chọn loại điểm!");
            return;
        }
        if (semester.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập học kỳ!");
            return;
        }
        // KIỂM TRA PHÂN CÔNG
        if (currentUser.getRoleId() == 2) {
            boolean allowed = false;
            for (TeachingAssignment ta : teacherAssignments) {
                if (ta.getSchoolClassId() == selectedClass.getId()&& ta.getSubjectId() == selectedSubject.getId()) {
                    allowed = true;
                    break;
                }
            }
            if (!allowed) {
                JOptionPane.showMessageDialog(this,"Bạn không được phân công dạy môn này ở lớp này!");
                return;
            }
        }
        // XÓA BẢNG CŨ
        tableModel.setRowCount(0);
        rowToStudentId.clear();

        // LẤY DANH SÁCH HỌC SINH
        List<StudentProfile> students= studentDAO.getByClass(selectedClass.getId());
        int row = 0;
        for (StudentProfile sp : students) {
            // Tìm điểm đã có trong database
            Grade existingGrade
                    = gradeDAO.getExistingGrade(sp.getId(),selectedSubject.getId(),examType,semester);
            double score = 0.0;
            if (existingGrade != null) {
                score = existingGrade.getScore();
            }
            // Hiển thị điểm cũ nếu đã có
            tableModel.addRow(
                    new Object[]{sp.getStudentCode(),sp.getFullName(),score});
            rowToStudentId.put(row,sp.getId());
            row++;
        }
        if (students.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Lớp này chưa có học sinh!");
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Subject subject = (Subject) cboSubject.getSelectedItem();
        String examType = (String) cboExamType.getSelectedItem();
        String semester = txtSemester.getText().trim();
        if (semester.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập học kỳ!");
            return;
        }
        if (subject == null || tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn môn học và tải danh sách học sinh trước!");
            return;
        }

        int successCount = 0;
        for (int row = 0; row < tableModel.getRowCount(); row++) {
            Integer studentId = rowToStudentId.get(row);
            if (studentId == null) {
                continue;
            }
            double score = ((Number) tableModel.getValueAt(row, 2)).doubleValue();

            Grade g = new Grade();
            g.setStudentProfileId(studentId);
            g.setSubjectId(subject.getId());
            g.setExamType(examType);
            g.setScore(score);
            g.setSemester(semester);

            if (gradeDAO.saveOrUpdate(g)) {
                successCount++;
            }
        }
        JOptionPane.showMessageDialog(this, "Đã lưu điểm cho " + successCount + " học sinh!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainMenuFrm(currentUser).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    private void customizeUI() {
        tableModel = new DefaultTableModel(new Object[]{"Mã HS", "Họ tên", "Điểm"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 2 ? Double.class : String.class;
            }
        };
        tblGrades.setModel(tableModel);   // gọi setModel() LẦN 2 ở đây, ghi đè lên model tạm trong initComponents()

        cboExamType.removeAllItems();
        cboExamType.addItem("Miệng");
        cboExamType.addItem("15 phút");
        cboExamType.addItem("Giữa kỳ");
        cboExamType.addItem("Cuối kỳ");
    }

    private void loadCombos() {
        cboClass.removeAllItems();
        cboSubject.removeAllItems();
        // ADMIN
        if (currentUser.getRoleId() == 1) {
            for (SchoolClass c : classDAO.getAll()) {
                cboClass.addItem(c);
            }
            for (Subject s : subjectDAO.getAll()) {
                cboSubject.addItem(s);
            }
            return;
        }

        // GIÁO VIÊN
        if (currentUser.getRoleId() == 2) {
            teacherAssignments = teachingAssignmentDAO.getByTeacherUserId(currentUser.getId());
            // Chỉ lấy lớp giáo viên được phân công
            for (TeachingAssignment ta : teacherAssignments) {
                if (!containsClass(ta.getSchoolClassId())) {
                    SchoolClass schoolClass = new SchoolClass();
                    schoolClass.setId(ta.getSchoolClassId());
                    schoolClass.setClassName(ta.getClassName());
                    cboClass.addItem(schoolClass);
                }
            }
            // Khi đổi lớp thì đổi danh sách môn
            cboClass.addActionListener(e -> loadSubjectsBySelectedClass());
            // Load môn cho lớp đầu tiên
            if (cboClass.getItemCount() > 0) {
                cboClass.setSelectedIndex(0);
                loadSubjectsBySelectedClass();
            }
        }
    }

    private void loadSubjectsBySelectedClass() {

        cboSubject.removeAllItems();

        SchoolClass selectedClass
                = (SchoolClass) cboClass.getSelectedItem();

        if (selectedClass == null || teacherAssignments == null) {
            return;
        }

        for (TeachingAssignment ta : teacherAssignments) {

            if (ta.getSchoolClassId() == selectedClass.getId()) {

                Subject subject = new Subject();

                subject.setId(
                        ta.getSubjectId()
                );

                subject.setSubjectName(
                        ta.getSubjectName()
                );

                subject.setSubjectCode(
                        ta.getSubjectCode()
                );

                cboSubject.addItem(subject);
            }
        }
    }

    private boolean containsClass(int classId) {
        for (int i = 0; i < cboClass.getItemCount(); i++) {
            SchoolClass c = cboClass.getItemAt(i);
            if (c.getId() == classId) {
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            model.User demoUser = new model.User();
            demoUser.setFullName("Quản trị viên");
            demoUser.setRoleId(1);

            new GradeEntryFrm(demoUser).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<SchoolClass> cboClass;
    private javax.swing.JComboBox<String> cboExamType;
    private javax.swing.JComboBox<Subject> cboSubject;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblExamType;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblGrades;
    private javax.swing.JTextField txtSemester;
    // End of variables declaration//GEN-END:variables
}
