/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.User;
import util.Session;

/**
 *
 * @author Lenovo
 */
public class MainMenuFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuFrm.class.getName());

    private final User currentUser;

    /**
     * Creates new form MainMenuFrm
     */
    public MainMenuFrm(User currentUser) {
        this.currentUser = currentUser;

        initComponents();
        setLocationRelativeTo(null);
        customizeUI();
        registerEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnStudents = new javax.swing.JButton();
        btnTeachers = new javax.swing.JButton();
        btnClasses = new javax.swing.JButton();
        btnSubjects = new javax.swing.JButton();
        btnGrades = new javax.swing.JButton();
        btnAttendance = new javax.swing.JButton();
        btnTuition = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnNotification = new javax.swing.JButton();
        btnSchedule = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnTeachingAssignment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWelcome.setText("Xin chào, <Họ tên> (<Role>)");

        btnStudents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnStudents.setText("Quản lý học sinh");

        btnTeachers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTeachers.setText("Quản lý giáo viên");

        btnClasses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClasses.setText("Quản lý lớp học");

        btnSubjects.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubjects.setText("Quản lý môn học");

        btnGrades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGrades.setText("Nhập điểm");

        btnAttendance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAttendance.setText("Điểm danh");

        btnTuition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTuition.setText("Quản lý học phí");

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnNotification.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNotification.setText("Thông báo");

        btnSchedule.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSchedule.setText("Thời khóa biểu");

        btnProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProfile.setText("Hồ sơ cá nhân");

        btnTeachingAssignment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTeachingAssignment.setText("Phân công giảng dạy");
        btnTeachingAssignment.addActionListener(this::btnTeachingAssignmentActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTeachingAssignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGrades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnTeachers, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addComponent(btnSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblWelcome)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStudents)
                    .addComponent(btnTeachers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClasses)
                    .addComponent(btnSubjects))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTeachingAssignment)
                    .addComponent(btnSchedule))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrades)
                    .addComponent(btnAttendance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNotification)
                    .addComponent(btnTuition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfile)
                    .addComponent(btnLogout))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void registerEvents() {

        //HỌC SINH
        btnStudents.addActionListener(e -> {

            int roleId = currentUser.getRoleId();

            if (roleId == 1 || roleId == 2) {
                this.dispose();
                new StudentManagementFrm(currentUser).setVisible(true);
            }
        });

        //GIÁO VIÊN
        btnTeachers.addActionListener(e -> {

            if (currentUser.getRoleId() == 1) {
                this.dispose();
                new TeacherManagementFrm().setVisible(true);
            }
        });

        //LỚP HỌC
        btnClasses.addActionListener(e -> {

            int roleId = currentUser.getRoleId();

            if (roleId == 1 || roleId == 2) {
                this.dispose();
                new ClassManagementFrm(currentUser).setVisible(true);
            }
        });

        //MÔN HỌC
        btnSubjects.addActionListener(e -> {

            if (currentUser.getRoleId() == 1) {
                this.dispose();
                new SubjectManagementFrm().setVisible(true);
            }
        });

        //THỜI KHÓA BIỂU
        btnSchedule.addActionListener(e -> {

            int roleId = currentUser.getRoleId();

            if (roleId == 1 || roleId == 2 || roleId == 3 || roleId == 4) {
                this.dispose();
                new ScheduleFrm(currentUser).setVisible(true);
            }
        });

        //ĐIỂM
        btnGrades.addActionListener(e -> {

            int roleId = currentUser.getRoleId();

            if (roleId == 1 || roleId == 2) {

                this.dispose();
                new GradeEntryFrm(currentUser).setVisible(true);

            } else if (roleId == 3 || roleId == 4) {

                JOptionPane.showMessageDialog(
                        this,
                        "Chức năng xem điểm đang được xây dựng.",
                        "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
        });

        //ĐIỂM DANH
        btnAttendance.addActionListener(e -> {

            int roleId = currentUser.getRoleId();

            if (currentUser.getRoleId() == 1 || currentUser.getRoleId() == 2) {
                this.dispose();
                new AttendanceFrm(currentUser).setVisible(true);
            } else if (roleId == 3) {

                JOptionPane.showMessageDialog(
                        this,
                        "Chức năng xem điểm danh đang được xây dựng.",
                        "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE
                );

            } else if (roleId == 4) {

                JOptionPane.showMessageDialog(
                        this,
                        "Chức năng xem điểm danh của con đang được xây dựng.",
                        "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
        });

        //HỌC PHÍ
        btnTuition.addActionListener(e -> {

            int roleId = currentUser.getRoleId();

            if (roleId == 1) {

                this.dispose();
                new TuitionFrm().setVisible(true);

            } else if (roleId == 4) {

                JOptionPane.showMessageDialog(
                        this,
                        "Chức năng xem học phí của con đang được xây dựng.",
                        "Thông báo",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
        });

        //THÔNG BÁO
        btnNotification.addActionListener(e -> {

            this.dispose();
            new NotificationFrm(currentUser).setVisible(true);
        });

        //HỒ SƠ
        btnProfile.addActionListener(e -> {
            this.dispose();
            new ProfileFrm(currentUser).setVisible(true);
        });
    }
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        util.Session.clear();
        this.dispose();
        new view.LoginFrm().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTeachingAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeachingAssignmentActionPerformed
        // TODO add your handling code here:
        if (currentUser.getRoleId() == 1
                || currentUser.getRoleId() == 2) {

            new TeachingAssignmentFrm(currentUser).setVisible(true);
        }
    }//GEN-LAST:event_btnTeachingAssignmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        User demoUser = new User();
        demoUser.setFullName("Quản trị viên (Demo)");
        demoUser.setRoleId(1);

        java.awt.EventQueue.invokeLater(() -> new MainMenuFrm(demoUser).setVisible(true));
    }

    private void customizeUI() {

        if (currentUser == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Không tìm thấy thông tin người dùng!",
                    "Lỗi",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            this.dispose();
            new LoginFrm().setVisible(true);
            return;
        }

        int roleId = currentUser.getRoleId();

        String roleName;

        switch (roleId) {
            case 1:
                roleName = "Admin";
                break;

            case 2:
                roleName = "Giáo viên";
                break;

            case 3:
                roleName = "Học sinh";
                break;

            case 4:
                roleName = "Phụ huynh";
                break;

            default:
                roleName = "Không xác định";
                break;
        }

        // Hiển thị lời chào
        lblWelcome.setText(
                "Xin chào, "
                + currentUser.getFullName()
                + " ("
                + roleName
                + ")"
        );

        // MẶC ĐỊNH KHÓA TẤT CẢ CHỨC NĂNG
        btnStudents.setEnabled(false);
        btnTeachers.setEnabled(false);
        btnClasses.setEnabled(false);
        btnSubjects.setEnabled(false);

        btnTeachingAssignment.setEnabled(false);
        btnSchedule.setEnabled(false);

        btnGrades.setEnabled(false);
        btnAttendance.setEnabled(false);

        btnTuition.setEnabled(false);
        btnNotification.setEnabled(false);

        btnProfile.setEnabled(true);

        // ROLE 1 - ADMIN
        if (roleId == 1) {

            btnStudents.setEnabled(true);
            btnTeachers.setEnabled(true);
            btnClasses.setEnabled(true);
            btnSubjects.setEnabled(true);

            btnTeachingAssignment.setEnabled(true);
            btnSchedule.setEnabled(true);

            btnGrades.setEnabled(true);
            btnAttendance.setEnabled(true);

            btnTuition.setEnabled(true);
            btnNotification.setEnabled(true);

            btnProfile.setEnabled(true);

            btnStudents.setText("Quản lý học sinh");
            btnTeachers.setText("Quản lý giáo viên");
            btnClasses.setText("Quản lý lớp học");
            btnSubjects.setText("Quản lý môn học");

            btnTeachingAssignment.setText("Phân công giảng dạy");
            btnSchedule.setText("Thời khóa biểu");

            btnGrades.setText("Nhập điểm");
            btnAttendance.setText("Điểm danh");

            btnTuition.setText("Quản lý học phí");
            btnNotification.setText("Thông báo");

            btnProfile.setText("Hồ sơ cá nhân");
        } // ROLE 2 - GIÁO VIÊN
        else if (roleId == 2) {

            btnStudents.setEnabled(true);
            btnClasses.setEnabled(true);

            btnTeachingAssignment.setEnabled(true);
            btnSchedule.setEnabled(true);

            btnGrades.setEnabled(true);
            btnAttendance.setEnabled(true);

            btnNotification.setEnabled(true);
            btnProfile.setEnabled(true);

            btnStudents.setText("Danh sách học sinh");
            btnTeachers.setText("Quản lý giáo viên");
            btnClasses.setText("Lớp giảng dạy");
            btnSubjects.setText("Quản lý môn học");

            btnTeachingAssignment.setText("Phân công giảng dạy");
            btnSchedule.setText("Thời khóa biểu");

            btnGrades.setText("Nhập điểm");
            btnAttendance.setText("Điểm danh");

            btnTuition.setText("Quản lý học phí");
            btnNotification.setText("Thông báo");

            btnProfile.setText("Hồ sơ cá nhân");
        } // ROLE 3 - HỌC SINH
        else if (roleId == 3) {

            btnSchedule.setEnabled(true);

            btnGrades.setEnabled(true);
            btnAttendance.setEnabled(true);

            btnNotification.setEnabled(true);
            btnProfile.setEnabled(true);

            btnStudents.setText("Quản lý học sinh");
            btnTeachers.setText("Quản lý giáo viên");
            btnClasses.setText("Quản lý lớp học");
            btnSubjects.setText("Quản lý môn học");

            btnTeachingAssignment.setText("Phân công giảng dạy");
            btnSchedule.setText("Thời khóa biểu");

            btnGrades.setText("Xem điểm");
            btnAttendance.setText("Xem điểm danh");

            btnTuition.setText("Quản lý học phí");
            btnNotification.setText("Thông báo");

            btnProfile.setText("Hồ sơ cá nhân");
        } // ROLE 4 - PHỤ HUYNH
        else if (roleId == 4) {

            btnSchedule.setEnabled(true);

            btnGrades.setEnabled(true);
            btnAttendance.setEnabled(true);
            btnTuition.setEnabled(true);

            btnNotification.setEnabled(true);
            btnProfile.setEnabled(true);

            btnStudents.setText("Quản lý học sinh");
            btnTeachers.setText("Quản lý giáo viên");
            btnClasses.setText("Quản lý lớp học");
            btnSubjects.setText("Quản lý môn học");

            btnTeachingAssignment.setText("Phân công giảng dạy");
            btnSchedule.setText("Thời khóa biểu của con");

            btnGrades.setText("Xem điểm của con");
            btnAttendance.setText("Xem điểm danh của con");

            btnTuition.setText("Xem học phí của con");
            btnNotification.setText("Thông báo");

            btnProfile.setText("Hồ sơ cá nhân");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnClasses;
    private javax.swing.JButton btnGrades;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNotification;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JButton btnStudents;
    private javax.swing.JButton btnSubjects;
    private javax.swing.JButton btnTeachers;
    private javax.swing.JButton btnTeachingAssignment;
    private javax.swing.JButton btnTuition;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
