/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ScheduleDAO;
import dao.SchoolClassDAO;
import dao.SubjectDAO;
import dao.TeacherDAO;

import model.Schedule;
import model.SchoolClass;
import model.Subject;
import model.TeacherProfile;
import model.User;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.Time;
import java.util.List;

/**
 *
 * @author Lenovo
 */
public class ScheduleFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScheduleFrm.class.getName());
    private final ScheduleDAO scheduleDAO = new ScheduleDAO();
    private final SchoolClassDAO classDAO = new SchoolClassDAO();
    private final SubjectDAO subjectDAO = new SubjectDAO();
    private final TeacherDAO teacherDAO = new TeacherDAO();

    private final User currentUser;

    private DefaultTableModel tableModel;

    private int selectedId = -1;

    public ScheduleFrm(User currentUser) {
        this.currentUser = currentUser;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        customizeUI();
        loadClassCombo();
        loadSubjectCombo();
        loadTeacherCombo();
        loadDayCombo();
        loadTable();
        registerEvents();
        setupRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblTeacher = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        lblStartTime = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        lblRoom = new javax.swing.JLabel();
        cboClass = new javax.swing.JComboBox<>();
        cboSubject = new javax.swing.JComboBox<>();
        cboTeacher = new javax.swing.JComboBox<>();
        cboDay = new javax.swing.JComboBox<>();
        txtStartTime = new javax.swing.JTextField();
        txtEndTime = new javax.swing.JTextField();
        txtRoom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("THỜI KHÓA BIỂU");

        lblClass.setText("Lớp:");

        lblSubject.setText("Môn học:");

        lblTeacher.setText("Giáo viên:");

        lblDay.setText("Thứ:");

        lblStartTime.setText("Giờ bắt đầu:");

        lblEndTime.setText("Giờ kết thúc:");

        lblRoom.setText("Phòng:");

        cboDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Lớp", "Môn học", "Giáo viên", "Thứ", "Bắt đầu", "Kết thúc", "Phòng"
            }
        ));
        jScrollPane1.setViewportView(tblSchedule);

        btnBack.setText("Quay lại");

        btnAdd.setText("Thêm");

        btnUpdate.setText("Sửa");

        btnDelete.setText("Xóa");

        btnClear.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnUpdate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboTeacher, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cboClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtStartTime)
                                            .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(lblSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblEndTime)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtEndTime)
                                            .addComponent(cboDay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(btnDelete)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnClear)))))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClass)
                            .addComponent(lblSubject)
                            .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTeacher)
                            .addComponent(lblDay)
                            .addComponent(cboTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStartTime)
                            .addComponent(lblEndTime)
                            .addComponent(txtStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRoom)
                            .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void customizeUI() {

        tableModel = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID",
                    "Lớp",
                    "Môn học",
                    "Giáo viên",
                    "Thứ",
                    "Bắt đầu",
                    "Kết thúc",
                    "Phòng"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblSchedule.setModel(tableModel);
        tblSchedule.setSelectionMode(
                javax.swing.ListSelectionModel.SINGLE_SELECTION
        );

        tblSchedule.setRowHeight(25);
    }

    private void registerEvents() {

        btnAdd.addActionListener(e -> addSchedule());

        btnUpdate.addActionListener(e -> updateSchedule());

        btnDelete.addActionListener(e -> deleteSchedule());

        btnClear.addActionListener(e -> clearForm());

        btnBack.addActionListener(e -> {

            this.dispose();

            new MainMenuFrm(currentUser).setVisible(true);
        });

        tblSchedule.getSelectionModel().addListSelectionListener(e -> {

            if (!e.getValueIsAdjusting()) {
                onRowSelected();
            }
        });
    }

    private void addSchedule() {
        SchoolClass selectedClass = (SchoolClass) cboClass.getSelectedItem();
        Subject selectedSubject = (Subject) cboSubject.getSelectedItem();
        TeacherProfile selectedTeacher = (TeacherProfile) cboTeacher.getSelectedItem();
        if (currentUser.getRoleId() != 1) {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền thêm thời khóa biểu!");
            return;
        }
        if (selectedClass == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn lớp!");
            return;
        }
        if (selectedSubject == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn môn học!");
            return;
        }

        if (selectedTeacher == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn giáo viên!");
            return;
        }
        if (txtStartTime.getText().trim().isEmpty() || txtEndTime.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giờ bắt đầu và giờ kết thúc!");
            return;
        }

        try {
            Time startTime = Time.valueOf(txtStartTime.getText().trim() + ":00");
            Time endTime = Time.valueOf(txtEndTime.getText().trim() + ":00");
            if (!startTime.before(endTime)) {
                JOptionPane.showMessageDialog(this, "Giờ bắt đầu phải nhỏ hơn giờ kết thúc!");
                return;
            }
            Schedule s = new Schedule();
            s.setSchoolClassId(selectedClass.getId());
            s.setSubjectId(selectedSubject.getId());
            s.setTeacherId(selectedTeacher.getId());
            s.setDayOfWeek(cboDay.getSelectedIndex());
            s.setStartTime(startTime);
            s.setEndTime(endTime);
            s.setRoom(txtRoom.getText().trim());
            if (scheduleDAO.insert(s)) {
                JOptionPane.showMessageDialog(this, "Thêm thời khóa biểu thành công!");
                loadTable();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thời khóa biểu thất bại!");
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Giờ phải nhập dạng HH:mm\nVí dụ: 07:00");
        }
    }

    private void deleteSchedule() {
        if (currentUser.getRoleId() != 1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Bạn không có quyền xóa thời khóa biểu!"
            );
            return;
        }
        if (selectedId == -1) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn thời khóa biểu cần xóa!"
            );

            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xóa thời khóa biểu này?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        if (scheduleDAO.delete(selectedId)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Xóa thành công!"
            );

            loadTable();

            clearForm();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Xóa thất bại!"
            );
        }
    }

    private void setupRole() {

        // Role 1 = Admin
        if (currentUser.getRoleId() == 1) {

            btnAdd.setEnabled(true);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            btnClear.setEnabled(true);

            cboClass.setEnabled(true);
            cboSubject.setEnabled(true);
            cboTeacher.setEnabled(true);
            cboDay.setEnabled(true);

            txtStartTime.setEnabled(true);
            txtEndTime.setEnabled(true);
            txtRoom.setEnabled(true);

        } // Role 2 = Giáo viên
        else if (currentUser.getRoleId() == 2) {

            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            btnClear.setEnabled(false);

            cboClass.setEnabled(false);
            cboSubject.setEnabled(false);
            cboTeacher.setEnabled(false);
            cboDay.setEnabled(false);

            txtStartTime.setEnabled(false);
            txtEndTime.setEnabled(false);
            txtRoom.setEnabled(false);
        }
    }

    private void onRowSelected() {

        int row = tblSchedule.getSelectedRow();

        if (row < 0) {
            return;
        }

        selectedId = Integer.parseInt(
                tableModel.getValueAt(row, 0).toString()
        );

        String className
                = tableModel.getValueAt(row, 1).toString();

        String subjectName
                = tableModel.getValueAt(row, 2).toString();

        String teacherName
                = tableModel.getValueAt(row, 3).toString();

        String dayName
                = tableModel.getValueAt(row, 4).toString();

        Object start
                = tableModel.getValueAt(row, 5);

        Object end
                = tableModel.getValueAt(row, 6);

        Object room
                = tableModel.getValueAt(row, 7);

        // Lớp
        for (int i = 0; i < cboClass.getItemCount(); i++) {

            SchoolClass c
                    = (SchoolClass) cboClass.getItemAt(i);

            if (c.toString().equals(className)) {

                cboClass.setSelectedIndex(i);

                break;
            }
        }

        // Môn học
        for (int i = 0; i < cboSubject.getItemCount(); i++) {

            Subject s
                    = (Subject) cboSubject.getItemAt(i);

            if (s.toString().equals(subjectName)) {

                cboSubject.setSelectedIndex(i);

                break;
            }
        }

        // Giáo viên
        for (int i = 0; i < cboTeacher.getItemCount(); i++) {

            TeacherProfile t
                    = (TeacherProfile) cboTeacher.getItemAt(i);

            if (t.getFullName().equals(teacherName)) {

                cboTeacher.setSelectedIndex(i);

                break;
            }
        }

        // Thứ
        for (int i = 0; i < ScheduleDAO.DAY_NAMES.length; i++) {

            if (ScheduleDAO.DAY_NAMES[i].equals(dayName)) {

                cboDay.setSelectedIndex(i);

                break;
            }
        }

        if (start != null) {

            String value = start.toString();

            txtStartTime.setText(
                    value.length() >= 5
                    ? value.substring(0, 5)
                    : value
            );
        }

        if (end != null) {

            String value = end.toString();

            txtEndTime.setText(
                    value.length() >= 5
                    ? value.substring(0, 5)
                    : value
            );
        }

        txtRoom.setText(
                room == null
                        ? ""
                        : room.toString()
        );
    }

    private void clearForm() {

        if (currentUser.getRoleId() != 1) {
            return;
        }

        selectedId = -1;

        if (cboClass.getItemCount() > 0) {
            cboClass.setSelectedIndex(0);
        }

        if (cboSubject.getItemCount() > 0) {
            cboSubject.setSelectedIndex(0);
        }

        if (cboTeacher.getItemCount() > 0) {
            cboTeacher.setSelectedIndex(0);
        }

        if (cboDay.getItemCount() > 0) {
            cboDay.setSelectedIndex(0);
        }

        txtStartTime.setText("");
        txtEndTime.setText("");
        txtRoom.setText("");

        tblSchedule.clearSelection();
    }

    private void loadClassCombo() {

        cboClass.removeAllItems();

        for (SchoolClass c : classDAO.getAll()) {
            cboClass.addItem(c);
        }
    }

    private void loadSubjectCombo() {

        cboSubject.removeAllItems();

        for (Subject s : subjectDAO.getAll()) {
            cboSubject.addItem(s);
        }
    }

    private void loadTeacherCombo() {

        cboTeacher.removeAllItems();

        for (TeacherProfile t : teacherDAO.getAll()) {
            cboTeacher.addItem(t);
        }
    }

    private void updateSchedule() {
        if (currentUser.getRoleId() != 1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Bạn không có quyền sửa thời khóa biểu!"
            );
            return;
        }
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn thời khóa biểu cần sửa!"
            );
            return;
        }

        SchoolClass selectedClass
                = (SchoolClass) cboClass.getSelectedItem();

        Subject selectedSubject
                = (Subject) cboSubject.getSelectedItem();

        TeacherProfile selectedTeacher
                = (TeacherProfile) cboTeacher.getSelectedItem();

        if (selectedClass == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn lớp!"
            );

            return;
        }

        if (selectedSubject == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn môn học!"
            );

            return;
        }

        if (selectedTeacher == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn giáo viên!"
            );

            return;
        }

        if (txtStartTime.getText().trim().isEmpty()
                || txtEndTime.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng nhập giờ bắt đầu và giờ kết thúc!"
            );

            return;
        }

        try {

            Time startTime = Time.valueOf(
                    txtStartTime.getText().trim() + ":00"
            );

            Time endTime = Time.valueOf(
                    txtEndTime.getText().trim() + ":00"
            );

            if (!startTime.before(endTime)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Giờ bắt đầu phải nhỏ hơn giờ kết thúc!"
                );

                return;
            }

            Schedule s = new Schedule();

            s.setId(selectedId);

            s.setSchoolClassId(selectedClass.getId());

            s.setSubjectId(selectedSubject.getId());

            s.setTeacherId(selectedTeacher.getId());

            s.setDayOfWeek(cboDay.getSelectedIndex());

            s.setStartTime(startTime);

            s.setEndTime(endTime);

            s.setRoom(txtRoom.getText().trim());

            if (scheduleDAO.update(s)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Cập nhật thời khóa biểu thành công!"
                );

                loadTable();

                clearForm();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Cập nhật thời khóa biểu thất bại!"
                );
            }

        } catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Giờ phải nhập dạng HH:mm\nVí dụ: 07:00"
            );
        }
    }

    private void loadTable() {
        tableModel.setRowCount(0);
        // ADMIN
        if (currentUser.getRoleId() == 1) {
            List<Object[]> list = scheduleDAO.getAll();
            for (Object[] row : list) {
                int day = Integer.parseInt(row[4].toString());
                tableModel.addRow(new Object[]{
                    row[0],
                    row[1],
                    row[2],
                    row[3],
                    ScheduleDAO.dayName(day),
                    row[5],
                    row[6],
                    row[7]
                });
            }

        } // GIÁO VIÊN
        else if (currentUser.getRoleId() == 2) {
            List<Object[]> list = scheduleDAO.getByTeacherUserId(currentUser.getId());
            for (Object[] row : list) {
                int day = Integer.parseInt(row[1].toString());
                tableModel.addRow(new Object[]{
                    row[0], // ID
                    row[3], // Lớp
                    row[2], // Môn học
                    currentUser.getFullName(), // Giáo viên
                    ScheduleDAO.dayName(day), // Thứ
                    row[4], // Bắt đầu
                    row[5], // Kết thúc
                    row[6] // Phòng
                });
            }
        }
    }

    private void loadDayCombo() {

        cboDay.removeAllItems();

        for (String day : ScheduleDAO.DAY_NAMES) {
            cboDay.addItem(day);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<SchoolClass> cboClass;
    private javax.swing.JComboBox<String> cboDay;
    private javax.swing.JComboBox<Subject> cboSubject;
    private javax.swing.JComboBox<TeacherProfile> cboTeacher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTeacher;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextField txtEndTime;
    private javax.swing.JTextField txtRoom;
    private javax.swing.JTextField txtStartTime;
    // End of variables declaration//GEN-END:variables
}
