/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.TeacherDAO;
import model.TeacherProfile;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import model.User;

/**
 *
 * @author Lenovo
 */
public class TeacherManagementFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeacherManagementFrm.class.getName());
    private DefaultTableModel tableModel;

    private final TeacherDAO teacherDAO = new TeacherDAO();

    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    private int selectedId = -1;
    private int selectedUserId = -1;

    /**
     * Creates new form TeacherManagementFrm
     */
    public TeacherManagementFrm() {
        initComponents();

        setLocationRelativeTo(null);

        customizeUI();
        registerEvents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeachers = new javax.swing.JTable();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        cboGender = new javax.swing.JComboBox<>();
        lblTeacherCode = new javax.swing.JLabel();
        txtTeacherCode = new javax.swing.JTextField();
        lblSpecialization = new javax.swing.JLabel();
        txtSpecialization = new javax.swing.JTextField();
        lblHireDate = new javax.swing.JLabel();
        txtHireDate = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ GIÁO VIÊN");

        tblTeachers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã GV", "Họ tên", "Chuyên môn", "Ngày vào làm"
            }
        ));
        jScrollPane1.setViewportView(tblTeachers);

        lblFullName.setText("Họ tên:");

        lblUsername.setText("Tên đăng nhập:");

        lblPassword.setText("Mật khẩu:");

        lblGender.setText("Giới tính:");

        cboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTeacherCode.setText("Mã GV:");

        lblSpecialization.setText("Chuyên môn:");

        lblHireDate.setText("Ngày vào làm (dd/MM/yyyy):");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(229, 229, 229))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblTeacherCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(12, 12, 12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtUsername)
                                                .addComponent(txtTeacherCode, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                            .addGap(51, 51, 51)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblSpecialization, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPassword)
                                        .addComponent(txtFullName)
                                        .addComponent(txtSpecialization, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHireDate, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtHireDate)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(btnAdd)
                                .addGap(47, 47, 47)
                                .addComponent(btnUpdate)
                                .addGap(46, 46, 46)
                                .addComponent(btnDelete)
                                .addGap(46, 46, 46)
                                .addComponent(btnClear)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullName)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeacherCode)
                    .addComponent(txtTeacherCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(cboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecialization)
                    .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHireDate)
                    .addComponent(txtHireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String fullName = txtFullName.getText().trim();
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim();
        String gender = (String) cboGender.getSelectedItem();
        String teacherCode = txtTeacherCode.getText().trim();
        String specialization = txtSpecialization.getText().trim();
        String hireDateText = txtHireDate.getText().trim();

        if (fullName.isEmpty()
                || username.isEmpty()
                || password.isEmpty()
                || teacherCode.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng nhập đầy đủ thông tin bắt buộc!"
            );

            return;
        }

        Date hireDate = null;

        if (!hireDateText.isEmpty()) {

            try {

                sdf.setLenient(false);

                hireDate = new Date(
                        sdf.parse(hireDateText).getTime()
                );

            } catch (ParseException e) {

                JOptionPane.showMessageDialog(
                        this,
                        "Ngày vào làm phải có dạng dd/MM/yyyy!"
                );

                return;
            }
        }

        boolean result = teacherDAO.insert(
                username,
                password,
                fullName,
                gender,
                teacherCode,
                specialization,
                hireDate
        );

        if (result) {

            JOptionPane.showMessageDialog(
                    this,
                    "Thêm giáo viên thành công!"
            );

            loadTable();
            btnClearActionPerformed(null);

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Thêm giáo viên thất bại!\n"
                    + "Username hoặc mã giáo viên có thể đã tồn tại."
            );
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (selectedId < 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn giáo viên trong bảng!"
            );

            return;
        }

        String teacherCode = txtTeacherCode.getText().trim();
        String fullName = txtFullName.getText().trim();
        String gender = (String) cboGender.getSelectedItem();
        String specialization = txtSpecialization.getText().trim();
        String hireDateText = txtHireDate.getText().trim();

        if (teacherCode.isEmpty() || fullName.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Mã giáo viên và họ tên không được để trống!"
            );

            return;
        }

        Date hireDate = null;

        if (!hireDateText.isEmpty()) {

            try {

                sdf.setLenient(false);

                hireDate = new Date(
                        sdf.parse(hireDateText).getTime()
                );

            } catch (ParseException e) {

                JOptionPane.showMessageDialog(
                        this,
                        "Ngày vào làm phải có dạng dd/MM/yyyy!"
                );

                return;
            }
        }

        TeacherProfile teacher = new TeacherProfile();

        teacher.setId(selectedId);
        teacher.setUserId(selectedUserId);
        teacher.setTeacherCode(teacherCode);
        teacher.setSpecialization(specialization);
        teacher.setHireDate(hireDate);

        boolean result = teacherDAO.update(
                teacher,
                fullName,
                gender
        );

        if (result) {

            JOptionPane.showMessageDialog(
                    this,
                    "Cập nhật giáo viên thành công!"
            );

            loadTable();
            btnClearActionPerformed(null);

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Cập nhật giáo viên thất bại!"
            );
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedId < 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn giáo viên trong bảng!"
            );

            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xóa giáo viên này?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        boolean result = teacherDAO.delete(
                selectedId,
                selectedUserId
        );

        if (result) {

            JOptionPane.showMessageDialog(
                    this,
                    "Xóa giáo viên thành công!"
            );

            loadTable();
            btnClearActionPerformed(null);

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Xóa giáo viên thất bại!\n"
                    + "Có thể giáo viên đang được sử dụng ở dữ liệu khác."
            );
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        selectedId = -1;
        selectedUserId = -1;

        txtTeacherCode.setText("");
        txtFullName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtSpecialization.setText("");
        txtHireDate.setText("");

        if (cboGender.getItemCount() > 0) {
            cboGender.setSelectedIndex(0);
        }

        tblTeachers.clearSelection();

        txtTeacherCode.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        this.dispose();

        User user = util.Session.getCurrentUser();

        if (user != null) {
            new MainMenuFrm(user).setVisible(true);
        } else {
            new LoginFrm().setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TeacherManagementFrm().setVisible(true));
    }

    private void customizeUI() {

        setTitle("Quản lý giáo viên");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableModel = new DefaultTableModel(
                new Object[]{
                    "ID",
                    "Mã GV",
                    "Họ tên",
                    "Chuyên môn",
                    "Ngày vào làm"
                }, 0) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblTeachers.setModel(tableModel);

        cboGender.removeAllItems();
        cboGender.addItem("Nam");
        cboGender.addItem("Nữ");

        tblTeachers.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                onRowSelected();
            }
        });
    }

    private void registerEvents() {

        btnAdd.addActionListener(e -> btnAddActionPerformed(e));

        btnUpdate.addActionListener(e -> btnUpdateActionPerformed(e));

        btnDelete.addActionListener(e -> btnDeleteActionPerformed(e));

        btnClear.addActionListener(e -> btnClearActionPerformed(e));

        btnBack.addActionListener(e -> btnBackActionPerformed(e));
    }

    private void loadTable() {

        tableModel.setRowCount(0);

        for (TeacherProfile t : teacherDAO.getAll()) {

            String hireDate = "";

            if (t.getHireDate() != null) {
                hireDate = sdf.format(t.getHireDate());
            }

            tableModel.addRow(new Object[]{
                t.getId(),
                t.getTeacherCode(),
                t.getFullName(),
                t.getSpecialization(),
                hireDate
            });
        }
    }

    private void onRowSelected() {

        int row = tblTeachers.getSelectedRow();

        if (row < 0) {
            return;
        }

        TeacherProfile teacher = teacherDAO.getAll().get(row);

        selectedId = teacher.getId();
        selectedUserId = teacher.getUserId();

        txtTeacherCode.setText(teacher.getTeacherCode());
        txtFullName.setText(teacher.getFullName());
        txtSpecialization.setText(
                teacher.getSpecialization() == null
                ? ""
                : teacher.getSpecialization()
        );

        if (teacher.getHireDate() != null) {
            txtHireDate.setText(
                    sdf.format(teacher.getHireDate())
            );
        } else {
            txtHireDate.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHireDate;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblTeacherCode;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTable tblTeachers;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtHireDate;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSpecialization;
    private javax.swing.JTextField txtTeacherCode;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
