/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.SchoolClassDAO;
import dao.SubjectDAO;
import dao.TeacherDAO;
import dao.TeachingAssignmentDAO;

import model.SchoolClass;
import model.Subject;
import model.TeacherProfile;
import model.TeachingAssignment;
import model.User;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class TeachingAssignmentFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeachingAssignmentFrm.class.getName());
    private final User currentUser;
    private final TeachingAssignmentDAO assignmentDAO = new TeachingAssignmentDAO();
    private final SchoolClassDAO classDAO = new SchoolClassDAO();
    private final SubjectDAO subjectDAO = new SubjectDAO();
    private final TeacherDAO teacherDAO = new TeacherDAO();
    private DefaultTableModel tableModel;
    private int selectedId = -1;

    /**
     * Creates new form TeachingAssignmentFrm
     */
    public TeachingAssignmentFrm(User currentUser) {

        this.currentUser = currentUser;

        initComponents();

        setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );

        setLocationRelativeTo(null);

        customizeUI();

        loadClassCombo();
        loadSubjectCombo();
        loadTeacherCombo();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAssignments = new javax.swing.JTable();
        lblClass = new javax.swing.JLabel();
        cboClass = new javax.swing.JComboBox<>();
        lblSubject = new javax.swing.JLabel();
        cboSubject = new javax.swing.JComboBox<>();
        lblTeacher = new javax.swing.JLabel();
        cboTeacher = new javax.swing.JComboBox<>();
        lblSchoolYear = new javax.swing.JLabel();
        txtSchoolYear = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("PHÂN CÔNG GIẢNG DẠY");

        btnBack.setText("Quay lại");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblAssignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lớp", "Môn học", "Mã môn", "Giáo viên", "Năm học"
            }
        ));
        jScrollPane1.setViewportView(tblAssignments);

        lblClass.setText("Lớp:");

        lblSubject.setText("Môn học:");

        lblTeacher.setText("Giáo viên:");

        lblSchoolYear.setText("Năm học:");

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(76, 76, 76)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdate))
                                    .addComponent(cboTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSchoolYear, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSchoolYear)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addGap(32, 32, 32)
                                .addComponent(btnClear)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClass)
                    .addComponent(cboClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubject)
                    .addComponent(cboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeacher)
                    .addComponent(cboTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSchoolYear)
                    .addComponent(txtSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        SchoolClass c= (SchoolClass) cboClass.getSelectedItem();
        Subject s= (Subject) cboSubject.getSelectedItem();
        TeacherProfile t= (TeacherProfile) cboTeacher.getSelectedItem();
        String schoolYear= txtSchoolYear.getText().trim();

        if (c == null
                || s == null
                || t == null
                || schoolYear.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }

        TeachingAssignment ta = new TeachingAssignment();

        ta.setSchoolClassId(c.getId());
        ta.setSubjectId(s.getId());
        ta.setTeacherProfileId(t.getId());
        ta.setSchoolYear(schoolYear);

        if (assignmentDAO.insert(ta)) {
            JOptionPane.showMessageDialog(this, "Thêm phân công thành công!");
            loadTable();
            clearForm();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Thêm phân công thất bại!"
            );
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (selectedId < 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn một phân công!"
            );

            return;
        }

        SchoolClass c
                = (SchoolClass) cboClass.getSelectedItem();

        Subject s
                = (Subject) cboSubject.getSelectedItem();

        TeacherProfile t
                = (TeacherProfile) cboTeacher.getSelectedItem();

        String schoolYear
                = txtSchoolYear.getText().trim();

        if (c == null
                || s == null
                || t == null
                || schoolYear.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng nhập đầy đủ thông tin!"
            );

            return;
        }

        TeachingAssignment ta
                = new TeachingAssignment();

        ta.setId(selectedId);
        ta.setSchoolClassId(c.getId());
        ta.setSubjectId(s.getId());
        ta.setTeacherProfileId(t.getId());
        ta.setSchoolYear(schoolYear);

        if (assignmentDAO.update(ta)) {

            JOptionPane.showMessageDialog(
                    this,
                    "Cập nhật thành công!"
            );

            loadTable();
            clearForm();

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Cập nhật thất bại!"
            );
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedId < 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn một phân công!"
            );

            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xóa phân công này?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            if (assignmentDAO.delete(selectedId)) {

                JOptionPane.showMessageDialog(
                        this,
                        "Xóa thành công!"
                );

                loadTable();
                clearForm();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        "Xóa thất bại!"
                );
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainMenuFrm(currentUser).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    private void clearForm() {

        selectedId = -1;

        txtSchoolYear.setText("");

        if (cboClass.getItemCount() > 0) {
            cboClass.setSelectedIndex(0);
        }

        if (cboSubject.getItemCount() > 0) {
            cboSubject.setSelectedIndex(0);
        }

        if (cboTeacher.getItemCount() > 0) {
            cboTeacher.setSelectedIndex(0);
        }

        tblAssignments.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    private void customizeUI() {

        tableModel = new DefaultTableModel(
                new Object[]{
                    "ID",
                    "Lớp",
                    "Môn học",
                    "Mã môn",
                    "Giáo viên",
                    "Năm học"
                },
                0
        ) {

            @Override
            public boolean isCellEditable(
                    int row,
                    int column
            ) {
                return false;
            }
        };

        tblAssignments.setModel(tableModel);

        tblAssignments.getSelectionModel()
                .addListSelectionListener(
                        e -> onRowSelected()
                );
    }

    private void loadClassCombo() {

        cboClass.removeAllItems();

        for (SchoolClass c : classDAO.getAll()) {
            cboClass.addItem(c);
        }
    }

    private void onRowSelected() {

        int row = tblAssignments.getSelectedRow();

        if (row < 0) {
            return;
        }

        selectedId
                = (int) tableModel.getValueAt(row, 0);

        String className
                = tableModel.getValueAt(row, 1).toString();

        String subjectCode
                = tableModel.getValueAt(row, 3).toString();

        String teacherName
                = tableModel.getValueAt(row, 4).toString();

        String schoolYear
                = tableModel.getValueAt(row, 5).toString();

        txtSchoolYear.setText(schoolYear);

        // Chọn lớp
        for (int i = 0;
                i < cboClass.getItemCount();
                i++) {

            SchoolClass c
                    = cboClass.getItemAt(i);

            if (c.getClassName()
                    .equals(className)) {

                cboClass.setSelectedIndex(i);
                break;
            }
        }

        // Chọn môn
        for (int i = 0;
                i < cboSubject.getItemCount();
                i++) {

            Subject s
                    = cboSubject.getItemAt(i);

            if (s.getSubjectCode()
                    .equals(subjectCode)) {

                cboSubject.setSelectedIndex(i);
                break;
            }
        }

        // Chọn giáo viên
        for (int i = 0;
                i < cboTeacher.getItemCount();
                i++) {

            TeacherProfile t
                    = cboTeacher.getItemAt(i);

            if (t.getFullName() != null
                    && t.getFullName()
                            .equals(teacherName)) {

                cboTeacher.setSelectedIndex(i);
                break;
            }
        }
    }

    private void loadSubjectCombo() {

        cboSubject.removeAllItems();

        for (Subject s : subjectDAO.getAll()) {
            cboSubject.addItem(s);
        }
    }

    private void loadTeacherCombo() {

        cboTeacher.removeAllItems();

        for (TeacherProfile t : teacherDAO.getAll()) {
            cboTeacher.addItem(t);
        }
    }

    private void loadTable() {

        tableModel.setRowCount(0);

        for (TeachingAssignment ta : assignmentDAO.getAll()) {

            tableModel.addRow(
                    new Object[]{
                        ta.getId(),
                        ta.getClassName(),
                        ta.getSubjectName(),
                        ta.getSubjectCode(),
                        ta.getTeacherName(),
                        ta.getSchoolYear()
                    }
            );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<SchoolClass> cboClass;
    private javax.swing.JComboBox<Subject> cboSubject;
    private javax.swing.JComboBox<TeacherProfile> cboTeacher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblSchoolYear;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTeacher;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblAssignments;
    private javax.swing.JTextField txtSchoolYear;
    // End of variables declaration//GEN-END:variables
}
